/*
 * Copyright © 2020 Mohamed Alaa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

package com.maproductions.mohamedalaa.processor

import com.maproductions.mohamedalaa.annotation.MAProviderOfAbstracts
import com.maproductions.mohamedalaa.annotation.MAAbstract
import com.maproductions.mohamedalaa.processor.custom_classes.SpecialAbstractProcessor
import com.maproductions.mohamedalaa.processor.extensions.*
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.metadata.KotlinPoetMetadataPreview
import com.squareup.kotlinpoet.metadata.toImmutableKmClass
import kotlinx.metadata.KmClassifier
import org.reflections.Reflections
import org.reflections.scanners.SubTypesScanner
import java.io.IOException
import javax.annotation.processing.RoundEnvironment
import javax.annotation.processing.SupportedAnnotationTypes
import javax.annotation.processing.SupportedSourceVersion
import javax.lang.model.SourceVersion
import javax.lang.model.element.TypeElement


/**
 * ## What this Processor does
 *
 * - Creates a MASpan.setup static fun which must be called on Application.onCreate fun by the
 * developer using this library to inject list of annotated classes in the Gson
 * serialization/deserialization process so core module of this library can do it's magic to
 * serialize/deserialize anything even abstract class, sealed class, interface, object class etc...
 *
 * ## How to Use
 *
 * - Any module that needs a class to be annotated then use annotation and processor on that
 * module isa, So use [MAAbstract] in that class.
 *
 * - If the class can't be annotated (due to being in a 3rd party library) then use
 * [MAProviderOfAbstracts] on any class that have properties of classes that required to be
 * annotated for ex. if ClassA is needed to be annotated and you can't do that, then create a class
 * called _ProviderOfAbstracts (or any name you want this is just a suggestion) like below code
 * ```
 * data class _ProviderOfAbstracts(
 *      var classA: ClassA
 * )
 * ```
 * Again this is not a must for the class to be a data class or named like that the only
 * requirement is to make a property (field) with a class that is needed to be treated like the
 * annotated classes.
 *
 * - On your Application.onCreate call MAGson.setup static fun generated by this processor.
 *
 * ## Tests on generated code
 *
 * - testing that generated code will be as expected isa.
 * - all modules below corresponds to modules in sample package.
 *
 * 1. Case where app depends on core & core2 -> Succeeded el7.
 * 2. Case where app depends on core3 which depends on core & core2 -> Succeeded el7.
 * 3. Case where app depends on core2 & core3 while both depend on core -> Succeeded el7.
 * 4. Case where app depends on core3 that depends on core2 that depends on core -> Succeeded el7.
 * 5. Same as case 4 but core 2 doesn't have annotations -> Succeeded el7.
 */
@KotlinPoetMetadataPreview
@SupportedAnnotationTypes(
    "com.maproductions.mohamedalaa.annotation.MAAbstract",
    "com.maproductions.mohamedalaa.annotation.MAProviderOfAbstracts",
)
@SupportedSourceVersion(SourceVersion.RELEASE_8)
class ProcessorOfFullNames : SpecialAbstractProcessor() {

    companion object {
        private const val generatedClassSimpleName = "MAGson"

        const val propertyName = "list"
    }

    private val specialClasses = listOf(
        "android.net.Uri"
    )

    private val generatedClassPackageName by lazy {
        MAAbstract::class.java.`package`.name + ".generated_as_internal_helper_package"
    }

    override fun processAnnotation(
        annotations: MutableSet<out TypeElement>,
        roundEnv: RoundEnvironment
    ): Boolean {
        // todo then if _GonConverter can be replaced by MATypes if not due to ? super wildcard to normal
        // then make in MATypes wildcard.eliminateWildcards isa. and check if works isa and del _GsonConverter
        // to remove duplicate code isa.

        /*
        todo then after processor is 100% isa, correct then adjust _Gson to make allANnotat... val
        be removed and use the one in $MA$Gson which will be planted and in tests since App not called
        nta b nafsak call MAGson.setup isa.
         */
        val classes = kotlin.runCatching {
            val reflections = Reflections(
                generatedClassPackageName,
                SubTypesScanner(false),
            )

            reflections.getSubTypesOf(Any::class.java)
        }.getOrNull().orEmpty()

        var fullNamesList = emptyList<String>()
        fullNamesList = fullNamesList + kotlin.runCatching {
            classes.mapNotNull { clazz ->
                val field = clazz.fields.firstOrNull { it.name == propertyName }
                    ?: return@mapNotNull null
                field.isAccessible = true
                @Suppress("UNCHECKED_CAST")
                val list = field.get(null) as List<Class<*>>
                list.mapNotNull {
                    if (it.isPrimitive) it.kotlin.javaObjectType.kotlin.qualifiedName else it.name
                }
            }.flatten()
        }.getOrNull().orEmpty()

        fullNamesList = fullNamesList + roundEnv.getElementsAnnotatedWith(MAAbstract::class.java)
            .filterIsInstance<TypeElement>().map { it.toImmutableKmClass().name.replaceForwardSlashWithDot() }

        for (element in roundEnv.getElementsAnnotatedWith(MAProviderOfAbstracts::class.java).filterIsInstance<TypeElement>()) {
            fullNamesList = fullNamesList + element.toImmutableKmClass().properties.mapNotNull {
                (it.returnType.classifier as? KmClassifier.Class)?.name?.replaceForwardSlashWithDot()
            }
        }

        if (fullNamesList.isEmpty()) {
            return false
        }

        // Exclude special classes isa.
        fullNamesList = fullNamesList - specialClasses

        // File Builder & Property & Functions
        val helperClassSimpleName = "_${System.nanoTime()}"
        val publicClassSimpleName = generatedClassSimpleName

        val helperClassFileSpecBuilder = FileSpec.builder(generatedClassPackageName, helperClassSimpleName)
        val publicClassFileSpecBuilder = FileSpec.builder(generatedClassPackageName, publicClassSimpleName)

        val propertySpecList = buildPropertySpecList(fullNamesList.distinct())
        val functionSpecSetup = buildFunctionSpecSetup(helperClassFileSpecBuilder, fullNamesList.distinct())
        val functionSpecGetLibUsedGson = buildFunctionSpecGetLibUsedGson(helperClassFileSpecBuilder)

        for (import in helperClassFileSpecBuilder.imports) {
            publicClassFileSpecBuilder.addImport(import)
        }

        // objects
        val helperClassObjectClass = TypeSpec.objectBuilder(helperClassSimpleName).apply {
            addProperty(propertySpecList)
        }.build()
        val publicClassObjectClass = TypeSpec.objectBuilder(publicClassSimpleName).apply {
            addFunction(functionSpecSetup)

            addFunction(functionSpecGetLibUsedGson)
        }.build()

        // files
        val helperClassFile = helperClassFileSpecBuilder
            .addSuppressUnusedAnnotation()
            .addType(helperClassObjectClass)
            .build()
        val publicClassFile = publicClassFileSpecBuilder
            .addSuppressUnusedAnnotation()
            .addType(publicClassObjectClass)
            .build()

        try {
            helperClassFile.writeTo(processingEnv.filer)
            publicClassFile.writeTo(processingEnv.filer)
        }catch (e: IOException) {
            e.printStackTrace()
        }

        return false
    }

    override fun getSupportedAnnotationTypes(): MutableSet<String> {
        return mutableSetOf(
            "com.maproductions.mohamedalaa.annotation.MAAbstract",
            "com.maproductions.mohamedalaa.annotation.MAProviderOfAbstracts",
        )
    }

    override fun getSupportedSourceVersion(): SourceVersion {
        return SourceVersion.RELEASE_8
    }

}
